/**
 * SEOFlowX White-Label Report Export Engine
 * Generates formatted CSV / Text export structures with agency branding headers.
 */

export interface ReportBrandingOptions {
  agencyName?: string;
  agencyWebsite?: string;
  clientName?: string;
  reportTitle: string;
}

export function formatBrandedCsvExport<T extends Record<string, unknown>>(
  data: T[],
  branding: ReportBrandingOptions,
): string {
  const headerLines = [
    `# ====================================================`,
    `# ${branding.reportTitle.toUpperCase()} - GENERATED BY SEOFLOWX`,
    `# Agency: ${branding.agencyName || "SEOFlowX Client Portal"}`,
    branding.agencyWebsite ? `# Website: ${branding.agencyWebsite}` : null,
    branding.clientName ? `# Client: ${branding.clientName}` : null,
    `# Date: ${new Date().toISOString().split("T")[0]}`,
    `# Data Source: DataForSEO API & SEOFlowX Engine`,
    `# ====================================================`,
    "",
  ]
    .filter(Boolean)
    .join("\n");

  if (data.length === 0) {
    return headerLines;
  }

  const columns = Object.keys(data[0]);
  const csvHeaders = columns.join(",");
  const csvRows = data.map((row) =>
    columns
      .map((col) => {
        const val = row[col];
        if (val === null || val === undefined) return '""';
        const str =
          typeof val === "string" ||
          typeof val === "number" ||
          typeof val === "boolean"
            ? String(val)
            : JSON.stringify(val);
        return `"${str.replace(/"/g, '""')}"`;
      })
      .join(","),
  );

  return `${headerLines}${csvHeaders}\n${csvRows.join("\n")}`;
}
